#!/bin/sh
git add -u && git status && \
    echo "Enter a commit message:" && \
    read commit_message && \
    git commit -m "$commit_message" && \
    if [ "$1" = "push" ]; then
	    git push
    fi
