#!/bin/bash

# Check if an argument is provided
if [ -n "$1" ]; then
    # Use the provided argument as the path
    selected_path="$1"
else
    # Use the current directory if no argument is provided
    selected_path="$(pwd)"
fi

# Run nsxiv with no bar and animate enabled
nsxiv --no-bar --animate "$selected_path"
