#!/bin/bash

# generate list
optlist=$(find "$HOME/documents/notes/" -type f | grep ".md$")
opttable=$(echo "$optlist" | awk -F"/" '{print $0, $NF, "("NR")"}')
optnames=$(echo "$opttable" | awk '{print $2, $3}')

# dmenu
uinp=$(echo "$optnames" | dmenu -i -p "Notes:")

# opttable lookup
selectedpath=$(echo "$opttable" | grep -m 1 "$uinp" | awk '{print $1}')

# open in nvim
[ -n "$uinp" ] && alacritty -e nvim $selectedpath
