#!/bin/bash

# generate list
optlist=$(find "$HOME/documents/notes/" -type f | grep ".md$")
opttable=$(echo "$optlist" | awk -F"/" '{print $NF "," $0}')

# dmenu
uinp=$(echo "$opttable" | dmenu -i -d "," -p "Notes:")

# open in nvim
[ -n "$uinp" ] \
	&& notify-send "opening $uinp" \
	&& st -e sh -c "nvim '$uinp'"
