#!/bin/bash
options="\nlogout\nsleep\nreboot\npower off\nrestart\nshutdown\nlock\nwifi toggle\nwifi off\nwifi on"
uinp="$(echo -e "$options" | dmenu -p "Power:")"
case $uinp in
	"logout") user_logout ;;
	"sleep") systemctl suspend ;;
	"reboot") reboot ;;
	"restart") reboot ;;
	"shutdown") shutdown -h now ;;
	"power off") shutdown -h now ;;
	"lock") xscreensaver-command -lock ;;
	"wifi toggle") wifitoggle ;;
	"wifi off") wifiset off;;
	"wifi on") wifiset on;;
	*) exit 0 ;; 
esac
