#!/bin/bash

# generate list
optlist=$(find "$HOME/documents/pictures/wallpaper/" -type f)
opttable=$(echo "$optlist" | awk -F"/" '{print $NF "," $0}')

# dmenu
uinp=$(echo "$opttable" | dmenu -i -d "," -p "Wallpaper:")

# set with feh
[ -n "$uinp" ] \
	&& notify-send -u "low" "setting wallpaper: $uinp" \
	&& fehset "$uinp"
