#!/bin/bash

# handle flags
while [[ "$#" -gt 0 ]]; do
    case $1 in
	-t|--title)
	    title="$2"
	    shift
	    ;;
        -m|--message)
            message="$2"
            shift
            ;;
        -u|--urgency)
            urgency="$2"
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [-u|--urgency] [-t|--title] [-m|--message] [-h|--help]"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
    shift
done

# Perform actions using flags
echo "Urgency: $urgency"
echo "Title: $title"
echo "Message: $message"

