#!/bin/sh
options="logout\nsleep\nrestart\nshutdown"
uinp="$(echo -e $options | dmenu -p "Power:")"
case $uinp in
	"logout") s_logout ;;
	"sleep") systemctl suspend ;;
	"restart") reboot ;;
	"shutdown") shutdown -h now ;;
	*) exit 0 ;; 
esac
