#!/bin/bash
[ -n "$1" ] && filename="$1"
extension="${filename##*.}"
case "$extension" in
    "py")   printf "Running as Python\n";
            python3 "$filename"     ;;
    *)      printf "Trying to shell check\n";
            shellcheck "$filename"  ;;
    
esac
