#!/bin/sh
optlist=""
#compile directory list
while IFS= read -r line; do
    optlist="$(printf "%s\n%s" "${optlist}" "$(find $line -type d)")"
done < "$RES/.vimdirs"
uinp="$(echo "$optlist" | dmenu -p "Vifm:" -i -l 5)"
#open nvim to a blank file with nerdtree
[ -n "$uinp" ] && st -e vifm "$uinp"
