#!/bin/bash

if [ -z "$1" ]; then
	echo "Error: Argument \$1 missing."
	exit 1
fi

mixer_state=$(amixer set Master "$1")
percentage=$(echo "$mixer_state" | grep -oE '[0-9]+%')
mute_state=$(echo $mixer_state | grep -o "\[on\]")

case "$mute_state" in
	"[on]")		notify-send -u "normal" -r "1002" "Sound: $percentage Unmuted"
			;;
	*)		notify-send -u "normal" -r "1002" "Sound: $percentage Muted"
			;;
esac
