#!/bin/sh
network="$(nmcli dev status | grep -e "wifi" -e "ethernet" | awk '{print $4}' | grep -v "-")"
[ "$network" = "" ] && network="X"
#echo "$network">"resources/networkinfo.txt"
printf "%s\\n" "${network:0:8}"
