#!/bin/sh
for battery in /sys/class/power_supply/BAT?*; do
	case "$(cat $battery/status)" in
		"Charging")	status="⚡" ;;
		*)		status=""   ;;
	esac
	capacity="$(cat "$battery/capacity")"
	[ status = "" ] && [ capacity -le 25 ] && warn="!"
	printf " %s%s%d%%" "$status" "$warn" "$capacity"; unset warn
done && printf "\\n"
