#!/bin/bash

# generate list
optlist=$(fd .\.pdf$ $HOME/downloads/ $HOME/documents/)
opttable=$(echo -e "\n$optlist" | awk -F"/" '{print substr($NF, 1, 50) "," $0 }')

# dmenu
uinp=$(echo "$opttable" | dmenu -i -d "," -p "Pdf:")

# open pdf with zathura
[ -n "$uinp" ] && notify-send -u "low" "Opening $uinp" && zathura "$uinp"
