#!/bin/sh

opts=$(find /mnt/ /run/media/$(whoami)/ -maxdepth 1 -mindepth 1)
opttable=$(echo "$opts" | awk -F"/" '{print $NF "," $0}')
userin=$(echo -e "\n$opttable" | dmenu -i -d "," -p "Unmount:")
[ -n "$userin" ] \
	&& notify-send "unmounting $userin" \
	&& udisksctl unmount -p "$userin" \
	&& udisksctl power-off -p "$userin"
