#!/bin/sh
mount_dir="/run/media/$(whoami)"
opts=$(ls "$mount_dir")
userin=$(echo -e "\n$opts" | dmenu -i -p "Unmount:")
target_dir="$mount_dir/$userin"
[ -n "$userin" ] \
	&& notify-send "unmounting $userin" \
	&& udiskie-umount --detach "$target_dir"
