#!/bin/bash

# generate list
optlist=$(find "$HOME/documents/notes/" -type f | grep ".md$")
opttable=$(echo -e  "\n*new note\n$optlist" | awk -F"/" '{print $NF "," $0}')

# dmenu
uinp=$(echo "$opttable" | dmenu -i -d "," -p "Notes:")

# new note
if [ "$uinp" = "*new note" ]; then
	newnotesmenu
	exit 0
fi

# file basename
note_name=$(basename "$uinp")

# open in nvim
[ -n "$uinp" ] \
	&& notify-send -u low "opening $note_name" \
	&& st_init -e "nvim '$uinp'"
