#!/bin/bash

# generate list
optlist=$(find "$HOME/documents/notes/" -type f | grep ".md$")
opttable=$(echo -e  "\n*new note\n$optlist" | awk -F"/" '{print $NF "," $0}')

# dmenu
uinp=$(echo "$opttable" | dmenu -i -d "," -p "Notes:")

# new note
if [ "$uinp" = "*new note" ]; then
	newnotesmenu
	exit 0
fi

# open in nvim
[ -n "$uinp" ] \
	&& notify-send "opening $uinp" \
	&& st -e sh -c "nvim '$uinp'"
