#!/bin/bash

config="$HOME/.config/dwmstatus/config.txt"

# dmenu
uinp=$(echo -e "\nless\nsystem\nsystem + fan\nnetwork" | dmenu -i -p "Status:")

# write to config (first line)
[ -n "$uinp" ] && sed -i "1s/.*/$uinp/" "$config"
