#!/bin/bash

# battery state
acpi_data=$(acpi -b | awk '/Battery 0/')
percent_charge=$(echo "$acpi_data" | awk '{print $4}')
charging_status=$(echo "$acpi_data" | awk '{print $3}' | sed 's/.$//')

# charging state icons
case "$charging_status" in
	"Charging")
		charging_status="󱐋"
		;;
	"Discharging")
		charging_status=""
		;;
	"Full")
		charging_status="󰁹"
		;;
	*)
		charging_status="󰂑"
		;;
esac

# output
echo "$charging_status $percent_charge"
